language: go
sudo: required
go:
  - 1.6.2
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-software-properties
  - sudo apt-add-repository -y ppa:mosquitto-dev/mosquitto-ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y mosquitto
  - go get github.com/golang/lint/golint
  - go get github.com/kisielk/errcheck

script:
  - make test

before_deploy:
  - sudo apt-get install -y python-pip
  - sudo pip install -r requirements.txt
  - mkdocs build

  - GOOS=linux GOARCH=amd64 make package
  - GOOS=linux GOARCH=386 make package
  - GOOS=linux GOARCH=arm make package
  - GOOS=darwin GOARCH=amd64 make package
  - GOOS=windows BINEXT=.exe GOARCH=386 make package
  - GOOS=windows BINEXT=.exe GOARCH=amd64 make package

deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: AKIAJYY7LKL2NK4UABXQ
    secret_access_key:
      secure: h5ku+etn/Y+CDyXoVIoImMgc5sP1cOjQ0rDSt60sdEUsboHHo7sFfPRybTppcTJwZe33bMl5/nrW0GGHpMpbotWB2ifxe/irRPsRpuXzy2lc0rq1DaT9mHK1SJ3VYEYjIJVH+G5GQFzt5cPxgPagkpPMZyLth+liCg0ry7tz/P1MxGg5Ltn9yIOKjyNBeEIKYGDzsyUlTDlTrN6xKmic9aHa5yulXdyS0r8XVZ6YqT/CLEWS2fF16XnQ3OqNXjh8beBHj7oRxj9Z/SWAS82PBO8WBBQ9wrT7JDuP7oSPKpjZPnbHcOxSCHiakzaVqGAJCTQJ7ndjIYLItQoKJxs1t2XM8NUd10o87d3XE5yDcGvFBkAI53oAIFa/2nmJSyNwBnutp8xg+JcuexxZKZsPwKk8mh0vIpmM0JcWTHIjW+ATskjUkMiX3ap/nn2uvGTBXIC4X9wSNKySkx0yKiM4nW+6U5fseAz4X9zkUby/STEGtIfGIaiFba3AH0d+Ld+qwzdS3RTLIWwIAdvWodekW2YPpeITsaBFpAyKxw5eTQ6GkgOOOV8se4sEY2EDarWlC/xAyPdIpJtveos8SR+uG8z9E030keglZLl49GjBbEgWrMwxAji9p/S3dY0SrBIHtKmEaP2lI7F8uL0dMG49yiY6LUcInhuOPkZ+oXnHn+c=
    bucket: docs.loraserver.io
    local-dir: site
    upload-dir: lora-gateway-bridge
    acl: public_read
    region: eu-west-1
    on:
      repo: brocaar/lora-gateway-bridge
      branch: master

  - provider: releases
    skip_cleanup: true
    api_key:
      secure: i9kTpzo0LVyMdMyN66SxXGBYovd98+B4DW9t/xFxx0cOzCwDKx/2p2WYF7cbT6FhVQVPZHJuIqatEFPVHgkRbiqsLIN26RL7xdCGV0gqjYoXVjJEdr6s9z1BhxUDGHY5oKhTZP7mHM+5jdHyZiwBbVFhJkeEbuZfwaOu7fho3IgGgnMASMh0LODk5niBnAJah1tMyUa5+7lW3fBAjwP2DNPICzIFm35JFjI5ViyirWcSapuTTE70BOH02PNd/wjx/4VnW5+wgCPeZXqjUQ5u94KHNLj5AxwotbzLNM1fDngJeDCmFMUPCjR+LCRnEO+4qhdMAhBdiTn0tXFoVQXlywrmfBdQtA3Kr8GSWHF1x2Oqr6/sIti0+fjyqdHRG2LdL7shEktBrG3muNUrVflpHXBzPOm9HvzQ7Hws6JudY52kermCeCRcbypcWz9PSK+XtAIbQxY0hO3cBRysNKjQ3K6IwPaUUqJzLrdowZ/LRhDur1JBXwc6cxS+4Yv885jUhIIfvFuM/lE1btK1zAtqVT1YVfXSpnMWk/FvBohHbQRy4i80Vd3an41hdM5Di/rPI8rkRaCqGRep3/FitKCVixvI1lKzgfRDFGLIBTBor0tL6tfD4T3ZuC/hRpTzI+UHx8XyO1RGZQIHNj3jIOJl+EBVYz+93KS3Z80v3uMj5ck=
    file_glob: true
    file: "dist/*.tar.gz"
    on:
      tags: true
      repo: brocaar/lora-gateway-bridge
